---
- hosts: AHI
  connection: network_cli
  gather_facts: no
  tasks:
  - name: config connection ssh with port 22822
    set_fact:
     ansible_port: 22822

  - name: config gws-onms
    routeros_command:
      commands:
      - ip firewall address-list add address=klgsys-1-t.cybereason.net list=GOOGLE
      - ip firewall address-list add address=klgsys-2-t.cybereason.net list=GOOGLE
      - ip firewall address-list add address=klgsys-3-t.cybereason.net list=GOOGLE
      - ip firewall address-list add address=klgsys-4-t.cybereason.net list=GOOGLE
      - ip firewall address-list add address=klgsys-5-t.cybereason.net list=GOOGLE
      - ip firewall address-list add address=klgsys-6-t.cybereason.net list=GOOGLE
      - ip firewall address-list add address=klgsys-7-t.cybereason.net list=GOOGLE
